spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI4G9REVX7tWQWQoNpFyRU
      secret-key: vzLeFVRV59GO4Uyj1O3wOPMURsuNW0
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: gulimall-gzy
  application:
    name: gulimall-third-party

server:
  port: 30000